eureka:
  client:
    service-url:
      defaultZone: http://localhost:8080/eureka/
server:
  port: 9090
spring:
  application:
    name: service-ribbon
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/student?useUnicode=true&characterEncoding=utf8
  redis:
    host: 192.168.142.128
    port: 6379
    pool:
      max-idle: 100
      min-idle: 1
      max-active: 1000
      max-wait: -1
pagehelper:
  dialect: com.github.pagehelper.dialect.helper.MySqlDialect


