eureka:
  client:
    service-url:
      defaultZone: http://localhost:8080/eureka/
server:
  port: 9090
spring:
  application:
    name: service-ribbon
  master:
    datasource:
      driver-class-name: com.mysql.jdbc.Driver
      username: root
      password: root
      url: jdbc:mysql://localhost:3306/student?useUnicode=true&characterEncoding=utf8
  slave:
    datasource:
      driver-class-name: com.mysql.jdbc.Driver
      username: root
      password: root
      url: jdbc:mysql://localhost:3306/shop?useUnicode=true&characterEncoding=utf8
  redis:
    host: 192.168.142.128
    port: 6379
    pool:
      max-idle: 100
      min-idle: 1
      max-active: 1000
      max-wait: -1
  auto: # 自动打开配置的浏览器
      openurl: true # 是否打开浏览器
  web:
      loginurl: http://localhost:9090 # 对应的服务名称
      googleexcute: C:\\Program Files (x86)\\Google\\Chrome\\Application\\chrome1.exe
pagehelper:
  dialect: com.github.pagehelper.dialect.helper.MySqlDialect




